version: '3'

services:
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ./:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=5

  
  automatic1111:
    build:
      context: .
      dockerfile: Dockerfile.automatic1111.cpu
    restart: unless-stopped
    network_mode: host
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 7860:7860
    volumes:
      - ./stable-diffusion:/content/stable-diffusion-webui/models/Stable-diffusion/
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - AUTOMATIC1111_BASE_URL=http://stable-diffusion-webui:7860
    ports:
      - 8080:8080
